# Generated by Django 4.2.3 on 2023-07-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_of_creation', models.DateField()),
                ('deadline_date', models.DateField()),
                ('priority_level', models.CharField(choices=[('Высокий', 'Высокий'), ('Средний', 'Средний'), ('Малый', 'Малый')], max_length=50)),
                ('status', models.CharField(choices=[('Не выполнено', 'Не выполнено'), ('Выполнено', 'Выполнено')], max_length=50)),
            ],
        ),
    ]
