# Generated by Django 4.2.3 on 2023-07-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline_date', 'priority_level']},
        ),
        migrations.AlterField(
            model_name='task',
            name='priority_level',
            field=models.CharField(choices=[(1, 'Высокий'), (2, 'Средний'), (3, 'Малый')], default=1, max_length=50),
        ),
    ]
